"""initial schema

Revision ID: e18ee75b19f6
Revises: 
Create Date: 2026-03-22 19:06:07.372348

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e18ee75b19f6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.Enum('USGS_3DEP', 'PASDA', 'WV', 'NY', 'OH', name='datasourceenum'), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('acquisition_year', sa.Integer(), nullable=True),
    sa.Column('resolution_m', sa.Float(), nullable=True),
    sa.Column('crs', sa.Integer(), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('tile_count', sa.Integer(), nullable=False),
    sa.Column('total_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'DOWNLOADING', 'DOWNLOADED', 'PROCESSING', 'READY', 'ERROR', name='tilestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ground_truth_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('feature_type', sa.Enum('SINKHOLE', 'CAVE_ENTRANCE', 'MINE_PORTAL', 'DEPRESSION', 'COLLAPSE_PIT', 'SPRING', 'UNKNOWN', name='featuretype'), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'PASDA_KARST', 'PA_AML', 'USGS_NY', 'USGS_NATIONAL', 'OHIO_EPA', name='groundtruthsource'), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ground_truth_geometry', 'ground_truth_sites', ['geometry'], unique=False, postgresql_using='gist')
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('INGEST', 'PROCESS', 'DETECT', 'FULL_PIPELINE', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('region', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('result_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('point_count', sa.Integer(), nullable=True),
    sa.Column('bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('crs', sa.Integer(), nullable=True),
    sa.Column('has_dem', sa.Boolean(), nullable=False),
    sa.Column('dem_path', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('DISCOVERED', 'DOWNLOADING', 'DOWNLOADED', 'PROCESSING', 'READY', 'ERROR', name='tilestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tile_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('feature_type', sa.Enum('SINKHOLE', 'CAVE_ENTRANCE', 'MINE_PORTAL', 'DEPRESSION', 'COLLAPSE_PIT', 'SPRING', 'UNKNOWN', name='featuretype'), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('outline', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('depth_m', sa.Float(), nullable=True),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('circularity', sa.Float(), nullable=True),
    sa.Column('depth_area_ratio', sa.Float(), nullable=True),
    sa.Column('wall_slope_deg', sa.Float(), nullable=True),
    sa.Column('source_passes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('morphometrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['tile_id'], ['tiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detections_geometry', 'detections', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index('ix_detections_type_confidence', 'detections', ['feature_type', 'confidence'], unique=False)
    op.create_table('pass_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('pass_name', sa.String(length=100), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('validation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=False),
    sa.Column('verdict', sa.Enum('CONFIRMED', 'REJECTED', 'UNCERTAIN', name='validationverdict'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('validation_events')
    op.drop_table('pass_results')
    op.drop_index('ix_detections_type_confidence', table_name='detections')
    op.drop_index('ix_detections_geometry', table_name='detections', postgresql_using='gist')
    op.drop_table('detections')
    op.drop_table('tiles')
    op.drop_table('jobs')
    op.drop_index('ix_ground_truth_geometry', table_name='ground_truth_sites', postgresql_using='gist')
    op.drop_table('ground_truth_sites')
    op.drop_table('datasets')
    # ### end Alembic commands ###
